name: Deploy Hugo site to S3

on:
    push:
        branches:
            - main
    workflow_dispatch:

permissions:
    contents: read
    id-token: write

concurrency:
  group: "hugo_deploy"
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            HUGO_VERSION: ${{ vars.HUGO_VERSION}}
        steps:
            - name: Install Hugo
              run: |
                wget -O ${{ runner.temp }}/hugo.deb https://GitHub.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb   
