name: Deploy Hugo site to S3

on:
  push:
    branches:
    - main
    paths:
    - "../../website/**"
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

concurrency:
  group: "hugo_deploy"
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      HUGO_VERSION: ${{ vars.HUGO_VERSION}}

    steps:
    - name: Checkout Branch
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install Hugo CLI
      run: |
        wget -O ${{ runner.temp }}/hugo.deb https://gitHub.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb; \
        sudo apt install ${{ runner.temp }}/hugo.deb

    - name: Build Hugo Site
      env:
        HUGO_ENVIRONMENT: production
        HUGO_ENV: production
      run: |
        cd website/portfolio
        hugo \
          --minify \
          --baseURL "${{ vars.SITE_BASE_URL }}/"

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.4.1
      with:
        name: hugo-site
        path: website/portfolio/public

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4.0.2
      with:
        aws-region: ${{ vars.AWS_REGION }}
        role-to-assume: ${{ vars.AWS_HUGO_ROLE }}
        role-session-name: gha-build-hugo

    - name: Download Build Artifacts
      uses: actions/download-artifact@v4
      with:
        name: hugo-site
        path: ./public

    - name: Sync Hugo Files to S3
      id: deployment
      run: aws s3 sync ./public/ s3://${{ vars.BUCKET_NAME }} --delete --cache-control max-age=31536000

    - name: Flush Cloudfront Cache
      id: flush_cache
      run: aws cloudfront create-invalidation --distribution-id ${{ vars.CF_DISTRIBUTION_ID }} --paths "/*"


